fix(backend): use 'require' instead of import to avoid TS errors
- while I still don't figure out how to fix the 'error TS2451: Cannot redeclare block-scoped variableerror TS2451: Cannot redeclare block-scoped variable', a require was used instead